services:
  pgvector:
    build:
      context: ./docker/pgvector
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  pgvector_data:
